config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  get 'manage', to: 'posts#manage'

  resources :posts do
    member do
      post   :like
      delete :like, action: :unlike, as: :unlike
      post   :dislike
      delete :dislike, action: :undislike, as: :undislike
    end
  end

  resources :sections, only: %w(index create update destroy)
  resources :tags, only: %w(index)

  devise_for :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable_on :tags
  belongs_to :user
  belongs_to :section

  validates :title, presence: true, length: 1..255
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: 1..255
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  recommends :posts

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  RECOMMENDABLE_METHODS = %w(like unlike dislike undislike).freeze

  before_action :set_post, only: %w(show edit update destroy).concat(RECOMMENDABLE_METHODS)
  before_action :fetch_sections, only: %w(index manage show edit update new create)
  before_action :post_owner, only: %w(edit update destroy)
  respond_to :json, only: RECOMMENDABLE_METHODS

  # GET /posts
  def index
    @q = Post.ransack(params[:q])
    @q.sorts = 'section_id asc' if @q.sorts.empty?
    @posts = @q.result(distinct: true)
  end

  # GEt /posts/manage
  def manage
    if current_user.admin?
      @posts = Post.all
    else
      @posts = current_user.posts
    end
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update

    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  RECOMMENDABLE_METHODS.each do |method|
    define_method(method) do
      @post = Post.find(params[:id])

      if current_user.send(method, @post)
        head :ok
      else
        head :unprocessable_entity
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def fetch_sections
    @sections = Section.all
  end

  # Only allow a trusted parameter 'white list' through.
  def post_params
    params.require(:post).permit(:title, :text, :annotation, :image_src, :section_id, :user_id, :author, tag_list: [])
  end

  def post_owner
    unless @post.user_id == current_user.id || current_user.admin?
      flash[:notice] = 'Access denied as you are not owner of this job'
      redirect_to posts_path
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %w(update destroy)

  def index
    @section = Section.new
    @sections = Section.all.order(:id)
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to sections_path, notice: 'Section was successfully created.'
    else
      redirect_to sections_path, notice: 'Some errors occurred.'
    end
  end

  def update
    if @section.update(section_params)
      redirect_to sections_path, notice: 'Section was successfully updated.'
    else
      redirect_to sections_path, notice: 'Some errors occurred.'
    end
  end

  # DELETE /sections/1
  def destroy
    @section.destroy
    redirect_to sections_path, notice: 'Section was successfully destroyed.'
  end

  private

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.all.order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(title, path, controller)
    "<li class=#{'active' if controller_name == controller}>
      #{link_to title, path}
    </li>".html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def str_date(date)
    date.strftime('%e %b %Y') if date
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Mazurik Blog
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    nav.navbar.navbar-default
      .container
        .navbar-header
          a.navbar-brand[href="/"]
            |  Mazurik Blog
        - if current_user
          ul.navbar-nav.nav
            = active_link_to 'Articles', posts_path, 'posts'
            /= active_link_to 'Sections', sections_path, 'sections'
        - if current_user.present? && current_page?(controller: 'posts', action: 'index')
          = search_form_for @q, html: { class: 'navbar-form navbar-left' }  do |f|
            .form-group
              = f.search_field :title_cont, placeholder: 'Search posts...', class: 'form-control'
            = f.submit 'Search', class: 'btn btn-default'
        ul.navbar-nav.nav.navbar-right
          - unless current_user
            li
              = link_to 'Sign up', new_user_registration_path
            li
              = link_to 'Sign in', new_user_session_path
          - else
            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
                = current_user.email
                | &nbsp;
                span.glyphicon.glyphicon-option-vertical
              ul.dropdown-menu
                li
                  = link_to 'My posts', manage_path
                li.divider
                li
                  = link_to 'Sign Out', destroy_user_session_path, method: :delete

    .container
      - if notice
        p.alert.alert-warning
          = notice
      = yield
      footer
        .text-center
          |  © Aleksey Mazurik. 2016

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  .form-group
    label.control-label
      | Author: &nbsp;
    = current_user.email
  = f.input :title, placeholder: 'Title...', hint: false
  = f.input :annotation, placeholder: 'Annotation...'
  = f.input :section_id, collection: @sections, selected: @post.section_id
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  .form-group
    label.control-label for='post[tag_list][]'
      | Tags:
    select.form-control.js-select2-select multiple="multiple" name="post[tag_list][]"
      - ActsAsTaggableOn::Tag.all.pluck(:name).each do |tag|
        - if tag.in?(@post.tag_list)
          option value="#{tag}" selected='selected' #{tag}
        - else
          option value="#{tag}" #{tag}
  = f.input :image_src, placeholder: 'Image URL...'
  = f.input :text, placeholder: 'Blog text type here...', input_html: {rows: '30'}
  = f.button :submit

app/views/posts/edit.html.slim
h1
  | Edit Post
= render 'form'

app/views/posts/index.html.slim
- @posts.each do |post|
  h3
    = post.section.name
    | &nbsp
    | &#8594;
    | &nbsp
    = link_to post do
      = post.title
    | &nbsp;
  p
    - post.tags.each do |tag|
      span.label.label-default
        = tag.name
  - if post.image_src.present?
    img src="#{post.image_src}" alt="Post image" width="100%"
  p
    = post.annotation
  = link_to 'Learn more &#8594;'.html_safe, post, class: 'btn btn-default'
  hr

app/views/posts/manage.html.slim
h1
  | Posts &nbsp;
  = link_to 'New Post', new_post_path, class: 'btn btn-sm btn-default'
- unless @posts.empty?
  table.table
    thead
      tr
        th Title
        th Annotation
        th Section
        th
    tbody
      - @posts.each do |post|
        tr
          td.min-200
            = link_to post.title, post
          td
            = post.annotation
          td.min-100
            = post.section.name
          td.min-130
            .text-left
              - if (current_user.id == post.user_id || current_user.admin?)
                = link_to 'Edit', edit_post_path(post), class: 'btn btn-sm  btn-warning'
                | &nbsp;
                = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
- else
  p
    |  No posts yet.

app/views/posts/new.html.slim
h1
  | New Post
= render 'form'

app/views/posts/show.html.slim
h2
  = @post.section.name
  | &nbsp
  | &#8594;
  | &nbsp
  = @post.title
  | &nbsp;
  - if (current_user.id == @post.user_id)
    = link_to 'Edit', edit_post_path(@post), class: 'btn btn-sm btn-default'

- if @post.image_src.present?
  = image_tag @post.image_src, alt: 'Post image', width: '100%'

p
  | By&nbsp;
  strong
    = @post.author

p
  strong
    | Created at: &nbsp;
  = str_date @post.created_at

h4
  - @post.tags.each do |tag|
    span.label.label-default
      = tag.name

p
  = @post.text.html_safe

.like-form-section
  - unless current_user.likes?(@post)
    = form_for @post, url: like_post_path, remote: true, method: :post, html: { class: 'form-inline like-form' } do |f|
      = f.button class: 'btn btn-default' do
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;Like
    | &nbsp;
  - else
    = form_for @post, url: unlike_post_path, remote: true, method: :delete, html: {class: 'form-inline like-form'} do |f|
      button.btn.btn-success type='submit'
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;Like
    | &nbsp;
  - unless current_user.dislikes?(@post)
    = form_for @post, url: dislike_post_path, remote: true, method: :post, html: {class: 'form-inline like-form'} do |f|
      button.btn.btn-default type='submit'
        span.glyphicon.glyphicon-thumbs-down
        | &nbsp;Dislike
    | &nbsp;
  - else
    = form_for @post, url: undislike_post_path, remote: true, method: :delete, html: {class: 'form-inline like-form'} do |f|
      button.btn.btn-danger type='submit'
        span.glyphicon.glyphicon-thumbs-down
        | &nbsp;Dislike


  - if current_user.recommended_posts.size > 0 && !(current_user.recommended_posts.include?(@post) && current_user.recommended_posts.size == 1)
    .also-like
      .panel.panel-default
        .panel-body
          h3 You may also like:
          - current_user.recommended_posts(4,0).each do |post|
            - if @post != post
              .media
                - if @post.image_src
                  .media-left
                    = link_to post do
                      img.media-object width="100" src="#{post.image_src}" alt='Post image'
                .media-body
                  = link_to post do
                    h4.media-heading #{post.title}
                  p #{post.annotation}

app/views/sections/index.html.slim
.sections
  .main-section
    h3.title
      | Technical sciences
    = image_tag 'computer_sciences.png'
  .sub-sections.row
    .section.col-md-4
      = image_tag 'social_media.jpg'
    .section.col-md-4
      = image_tag 'economics.jpg'
    .section.col-md-4
      = image_tag 'legal_sciences.jpg'

table.table.table-hover
  thead
    tr
      th #
      th Name
      - if current_user.admin?
        th Options
  tbody
    - if current_user.admin?
      tr.info
        td
        td
          = simple_form_for @section, method: :post, html: { class: 'form-inline' } do |f|
            .form-group
              = f.input :name, required: true, placeholder: 'Section name...', label: false
            = f.button :submit, 'Add Section', class: 'btn-sm'
    - @sections.each do |section|
      tr
        td #{section.id}
        td class='hidden js-edit-form' data-id="#{section.id}"
          = simple_form_for section, method: :put, html: { class: 'form-inline' } do |f|
            .form-group
              = f.input :name, placeholder: 'Section name...', required: true, label: false
            = f.button :submit, 'Update', class: 'btn btn-sm btn-primary'
            .form-group
              button class='btn btn-default js-cancel btn-sm' data-id="#{section.id}" Cancel
        td class='js-info-name' data-id="#{section.id}" #{section.name}
        - if current_user.admin?
          td.text-left
            button class='js-edit btn btn-sm btn-warning' data-id="#{section.id}"
              | Edit
            | &nbsp;
            = link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/tags/index.html.slim
table.table
  thead
    tr
      th
        | #
      th
        | Name
  tbody
    - @tags.each do |tag|
      tr
        td
          = tag.id
        td
          = tag.name